### ISSUE TITLE
BOT SAYS HI

### ISSUE THREAD

**Issue by sim33-k** [MurshidAkram/practical1#1]
hi

**Comment by sim33-k** [comment]
I Miss her <3

**Comment by sim33-k** [comment]
Thats what she said

**Comment by sim33-k** [comment]
![Uploading 296e315f-6db6-4621-9a53-153ddc067df4.jpeg…]()

**Comment by sim33-k** [comment]
![cee70f25-ca9f-4866-b190-6f86b6788c91](https://github.com/MurshidAkram/practical1/assets/138744378/aa98d408-109a-4c7d-8c81-f7e1bc877ee0)

**Comment by MurshidAkram** [comment]
Noice

**Comment by sim33-k** [comment]
![Screenshot from 2024-02-13 21-26-28](https://github.com/MurshidAkram/practical1/assets/138744378/7b024514-ff45-44ef-aa9d-285b8040280d)

**Comment by MurshidAkram** [comment]
issue is closed

**Comment by sim33-k** [comment]
Why is he mad if its not him?

**Comment by sim33-k** [comment]
_         _
  __   ___.--'_`.     .'_`--.___   __
 ( _`.'. -   'o` )   ( 'o`   - .`.'_ )
 _\.'_'      _.-'     `-._      `_`./_
( \`. )    //\`         '/\\    ( .'/ )
 \_`-'`---'\\__,       ,__//`---'`-'_/
  \`        `-\         /-'        '/
   `                               '   VK
